### ISSUE TITLE
Discord CTA & Footer

### ISSUE THREAD

**Issue by lihaoquan** [nus-gdg/nus-gdg.github.io#9]

**Comment by Singa-pirate** [comment]
Checked that both [red hat display](https://fonts.google.com/specimen/Red+Hat+Display/about?query=red+hat+display) and  [leckerli one](https://fonts.google.com/specimen/Leckerli+One/about?query=lecker) are open source, no need to credit them

**Comment by Singa-pirate** [comment]
Can I clarify these 2 requirements @lihaoquan @nknguyenhc 
- should this be changed to 2024 GDG?
![image](https://github.com/nus-gdg/nus-gdg.github.io/assets/58817781/4882a982-e28f-439a-9698-e9163db66442)
- should any icons / images be credited in the footer?

**Comment by nknguyenhc** [comment]
> Can I clarify these 2 requirements @lihaoquan @nknguyenhc
> 
> * should this be changed to 2024 NUSGDG?
>   ![image](https://private-user-images.githubusercontent.com/58817781/341126211-4882a982-e28f-439a-9698-e9163db66442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTA2OTQsIm5iZiI6MTcxODgxMDM5NCwicGF0aCI6Ii81ODgxNzc4MS8zNDExMjYyMTEtNDg4MmE5ODItZTI4Zi00MzlhLTk2OTgtZTkxNjNkYjY2NDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmViMzRkODMwNWVhYjE3NTRlYWJiYzAyYjU1ZDIxOTA3NGVmM2EyMjk0M2MzYjM2ZGM4NjE1NzBhMDY5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FT48W-AnLmj1Aqqqjmqxh3Z3bqUhhF3wP9Pi--u-7o)
> * should any icons / images be credited in the footer?

1. Yes, should be changed to 2024
2. No, we will be using images/icons provided by pubs. We can use placeholder images imported from figma for now.

**Comment by Singa-pirate** [comment]
@nknguyenhc 
The sticky nav bar and the footer contain similar elements, which can be visually distracting
![image](https://github.com/nus-gdg/nus-gdg.github.io/assets/58817781/382e42cd-7162-4aff-b8fd-8b886d7f4bff)

I'll add logic to nav bar, so that it disappears upward when the footer is in view, and reappears when the footer is no longer in view. LMK if you have better ideas to solve it.

**Comment by nknguyenhc** [comment]
@Singa-pirate In future we are planning to have sublinks in footer, and also under the logo on the left, there should be some text. I dont think we need to do anything with that for now.
